name: Build Android APK
on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK
        uses: valerii-kyryliuk/website-to-android-app-action@v1.1
        with:
          websiteUrl: 'https://anath9807.github.io/Testprox/'
          appName: 'TEST PRO'
          packageName: 'com.vinay.testpro'
