name: Generate APK
on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Website to APK
        uses: Swisyn/website-to-apk-action@v1.1
        with:
          websiteUrl: 'https://anath9807.github.io/Testprox/'
          appName: 'TEST PRO'
